language: python
python:
  - "2.7"
install:
  # install requirements
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
script:
  - ./functional_test.sh
after_success:
  - ./build_pkg.sh
deploy:
    provider: releases
    api_key: 7baf360dde232c5933de91551e296f7baf63f7eb
    file: "ucenter*.tar.gz"
    skip_cleanup: true
    on:
      tags: true
      branch: master
